spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/chungnam_thon
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

redis:
  main:
    host: ${REDIS_MAIN_HOST:localhost}
    port: 6379

# JWT 설정 (토큰 만료 시간을 초 단위로 설정)
jwt:
  secret: ${JWT_SECRET:ZGVmYXVsdFNlY3JldEtleUZvckpXVFRva2VuVGhhdElzUmVhbGx5TG9uZ0FuZFNlY3VyZUZvclByb2R1Y3Rpb24=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_VALIDITY:3600}    # 1시간 (3600초)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_VALIDITY:1209600} # 14일 (1209600초)

# Discord 알림 설정
discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL:https://discord.com/api/webhooks/1395237547109781504/iS3I4t2BYbX3hsvnlbX1Js0CeMKZ_vxi8Oqhpq0opPrlqsM1V9jLfqVS-QO_abxIpTde}

logging:
  config: classpath:logback-spring.xml

